- name: Deploy Custom Nginx to K3d
  hosts: localhost
  connection: local
  tasks:
    - name: Create Nginx Deployment
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: nginx-custom
            namespace: default
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: nginx-custom
            template:
              metadata:
                labels:
                  app: nginx-custom
              spec:
                containers:
                - name: nginx
                  image: my-nginx-custom:latest
                  imagePullPolicy: Never 
                  ports:
                  - containerPort: 80

    - name: Create Nginx Service
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: nginx-service
          spec:
            type: NodePort
            selector:
              app: nginx-custom
            ports:
            - port: 80
              targetPort: 80
              nodePort: 30080
