- name: Deploy nginx app on K3d
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    ansible_python_interpreter: /usr/bin/python3
    k8s_namespace: demo

  tasks:
    - name: Create namespace
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: "{{ k8s_namespace }}"

    - name: Create nginx deployment
      kubernetes.core.k8s:
        state: present
        namespace: "{{ k8s_namespace }}"
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: nginx-custom
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: nginx-custom
            template:
              metadata:
                labels:
                  app: nginx-custom
              spec:
                containers:
                  - name: nginx
                    image: my-nginx-custom:latest
                    imagePullPolicy: Never 
                    ports:
                      - containerPort: 80

    - name: Expose nginx service
      kubernetes.core.k8s:
        state: present
        namespace: "{{ k8s_namespace }}"
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: nginx-custom-service
          spec:
            type: NodePort
            selector:
              app: nginx-custom
            ports:
              - port: 80
                targetPort: 80
                nodePort: 30081
