---
- name: Deploiement de mon Nginx custom
  hosts: localhost
  connection: local
  tasks:
    - name: Création des ressources Kubernetes (Deployment et Service)
      kubernetes.core.k8s:
        state: present
        definition:
          - apiVersion: apps/v1
            kind: Deployment
            metadata:
              name: custom-nginx
              namespace: default
            spec:
              replicas: 2
              selector:
                matchLabels:
                  app: custom-nginx
              template:
                metadata:
                  labels:
                    app: custom-nginx
                spec:
                  containers:
                  - name: nginx
                    image: my-nginx-custom:latest
                    imagePullPolicy: Never
                    ports:
                    - containerPort: 80

          - apiVersion: v1
            kind: Service
            metadata:
              name: custom-nginx-service
              namespace: default
            spec:
              type: NodePort
              selector:
                app: custom-nginx
              ports:
              - port: 80
                targetPort: 80
