- name: Deploiement de mon Nginx custom
  hosts: localhost
  connection: local
  tasks:
    - name: Appliquer le Deployment via Shell
      shell: |
        cat <<EOF | kubectl apply -f -
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: nginx-custom
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: mon-web
          template:
            metadata:
              labels:
                app: mon-web
            spec:
              containers:
              - name: nginx-container
                image: my-nginx-custom:latest
                imagePullPolicy: Never
                ports:
                - containerPort: 80

    - name: Appliquer le Service via Shell
      shell: |
        cat <<EOF | kubectl apply -f -
        apiVersion: v1
        kind: Service
        metadata:
          name: nginx-service
        spec:
          type: NodePort
          selector:
            app: mon-web
          ports:
          - port: 80
            targetPort: 80
            nodePort: 30080
