- name: Deploy Custom Nginx to K3d
  hosts: localhost
  connection: local
  tasks:
    - name: Apply Nginx Deployment and Service
      kubernetes.core.k8s:
        state: present
        definition:

          - apiVersion: apps/v1
            kind: Deployment
            metadata:
              name: custom-nginx
            spec:
              replicas: 2
              selector:
                matchLabels:
                  app: custom-nginx
              template:
                metadata:
                  labels:
                    app: custom-nginx
                spec:
                  containers:
                  - name: nginx
                    image: my-custom-nginx:latest
                    imagePullPolicy: Never
                    ports:
                    - containerPort: 80

          - apiVersion: v1
            kind: Service
            metadata:
              name: custom-nginx-service
            spec:
              type: NodePort
              selector:
                app: custom-nginx
              ports:
              - port: 80
                targetPort: 80
